#! /bin/sh
#
# Docker wrapper script for common commands.

TAG="jasonish/snort:2.9.7.2"
CIDFILE="./cid"
OINKCODE_FILE="./data/etc/oinkcode"

if [ -e ./config ]; then
    . ./config

    # Also use the file as a Docker env-file.
    ENV_FILE="--env-file=./config"
fi

build() {
    docker build --rm -t ${TAG} image
}

run() {
    if tty > /dev/null; then
        tty="--tty"
    fi
    exec docker run ${tty} -i --rm --net=host ${ENV_FILE} \
	   -v $(pwd)/data:/data \
	   ${VOLUMES} \
	   ${DOCKER_ARGS} ${TAG} "$@"
}

usage() {
    cat <<EOF
usage: $0 <command> [args...]

commands:

    run [command]        - Default to a shell.
    build                - (Re)builds the container.
 
EOF
}

case "$1" in

    build)
	build
	;;

    run)
	shift
	run "$@"
	;;

    *)
	usage
	;;

esac
