#! /bin/sh
#
# Docker wrapper script for common commands.

TAG="jasonish/snort:2.9.7.2"
CIDFILE="./cid"

if [ -e ./config ]; then
    . ./config
fi

build() {
    docker build --rm -t ${TAG} image
}

prep() {
    mkdir -p data/etc/snort/rules
    mkdir -p data/var/lib/snort_dynamicrules
    mkdir -p data/var/log/snort
    mkdir -p data/var/tmp/snort
    test -e data/etc/snort/rules/snort.rules || \
	touch data/etc/snort/rules/snort.rules
    test -e data/etc/snort/rules/white_list.rules || \
	touch data/etc/snort/rules/white_list.rules
    test -e data/etc/snort/rules/black_list.rules || \
	touch data/etc/snort/rules/black_list.rules
}

run() {
    prep
    docker run -i -t --rm --net=host \
	   -v $(pwd)/data:/data \
	   ${DOCKER_ARGS} ${TAG} "$@"
}

usage() {
    cat <<EOF
usage: $0 <command> [args...]

commands:

    run [command]        - Default to a shell.
    prep                 - Prepares the container.
    build                - (Re)builds the container.
 
EOF
}

case "$1" in

    build)
	build
	;;

    prep)
	set -x
	prep
	;;

    run)
	shift
	run "$@"
	;;

    *)
	usage
	;;

esac
