#! /bin/sh
#
# Entry point script to make sure external volumes are properly prepped.

prepare_snort_files_and_directories() {
    if [ ! -e /data/etc/snort ]; then
	mkdir -p /data/etc
	cp -a /etc/snort /data/etc
    fi
    mkdir -p /data/etc/snort/rules
    mkdir -p /data/var/lib/snort_dynamicrules
    mkdir -p /data/var/log/snort
    mkdir -p /data/var/tmp/snort
    test -e /data/etc/snort/rules/snort.rules || \
	touch /data/etc/snort/rules/snort.rules
    test -e /data/etc/snort/rules/white_list.rules || \
	touch /data/etc/snort/rules/white_list.rules
    test -e /data/etc/snort/rules/black_list.rules || \
	touch /data/etc/snort/rules/black_list.rules
}

init_pulledpork() {
    ENABLESID_CONF=/data/etc/snort/enablesid.conf
    DISABLESID_CONF=/data/etc/snort/disablesid.conf
    DROPSID_CONF=/data/etc/snort/dropsid.conf
    MODIFYSID_CONF=/data/etc/snort/modifysid.conf

    if [ ! -e ${ENABLESID_CONF} ]; then
	cp /opt/pulledpork/etc/$(basename ${ENABLESID_CONF}) ${ENABLESID_CONF}
    fi
    if [ ! -e ${DISABLESID_CONF} ]; then
	cp /opt/pulledpork/etc/$(basename ${DISABLESID_CONF}) ${DISABLESID_CONF}
    fi
    if [ ! -e ${DROPSID_CONF} ]; then
	cp /opt/pulledpork/etc/$(basename ${DROPSID_CONF}) ${DROPSID_CONF}
    fi
    if [ ! -e ${MODIFYSID_CONF} ]; then
	cp /opt/pulledpork/etc/$(basename ${MODIFYSID_CONF}) ${MODIFYSID_CONF}
    fi
}

if [ ! -d /data ]; then
    echo "warning: /data is not mounted as a volume"
fi

prepare_snort_files_and_directories
init_pulledpork

if [ ! "$1" ]; then
   exec /bin/bash
fi

exec "$@"
